import { ICard } from "../types/drinks";

export const img = (ingredient: string, size: string) => {
    return `https://www.thecocktaildb.com/images/ingredients/${ingredient}${size}.png`
}

export const setImages = (images: string[], ingredients: ICard) => {
    Object.entries(ingredients).filter(entry =>
        entry[0].includes('strIngredient')).filter(entry =>
            entry[1] !== null).forEach(entry =>
                images.push(entry[1]));
}

export const setMeasures = (measures: string[], ingredients: ICard) => {
    Object.entries(ingredients).filter(entry =>
        entry[0].includes('strMeasure')).filter(entry =>
            entry[1] !== null).forEach(entry =>
                measures.push(entry[1]));
}

export const ingredients = [
    "151 proof rum",
    "7-Up",
    "Absinthe",
    "Absolut Citron",
    "Absolut Kurant",
    "Absolut Peppar",
    "Absolut Vodka",
    "Advocaat",
    "Agave Syrup",
    "Allspice",
    "Amaretto",
    "Amaro Montenegro",
    "Añejo rum",
    "Angostura Bitters",
    "Anis",
    "Anisette",
    "Aperol",
    "Apfelkorn",
    "Apple",
    "Apple brandy",
    "Apple juice",
    "Applejack",
    "Apricot brandy",
    "Apricot Nectar",
    "Asafoetida",
    "Bacardi Limon",
    "Baileys irish cream",
    "Banana",
    "Banana liqueur",
    "Beer",
    "Benedictine",
    "Bitter lemon",
    "Bitters",
    "Black pepper",
    "Black Sambuca",
    "Blackberries",
    "Blackberry brandy",
    "Blackcurrant cordial",
    "blackstrap rum",
    "Blended Scotch",
    "Blended whiskey",
    "Blood Orange",
    "Blue Curacao",
    "Bourbon",
    "Brandy",
    "Brown sugar",
    "Butter",
    "Butterscotch schnapps",
    "Cachaca",
    "Campari",
    "Caramel coloring",
    "Carbonated soft drink",
    "Carbonated water",
    "Cardamom",
    "Cayenne pepper",
    "Celery salt",
    "Chambord raspberry liqueur",
    "Champagne",
    "Cherries",
    "Cherry",
    "Cherry brandy",
    "Cherry Heering",
    "Cherry Juice",
    "Cherry liqueur",
    "Chocolate",
    "Chocolate liqueur",
    "Chocolate syrup",
    "Cider",
    "Cinnamon",
    "Cloves",
    "Club soda",
    "Coca-Cola",
    "Cocoa powder",
    "Coconut Liqueur",
    "Coconut milk",
    "Coconut syrup",
    "Coffee",
    "Coffee brandy",
    "Coffee liqueur",
    "Cognac",
    "Cointreau",
    "Condensed milk",
    "Coriander",
    "Corn syrup",
    "Corona",
    "Cranberry juice",
    "Cranberry vodka",
    "Cream",
    "Cream of coconut",
    "Creme de Banane",
    "Creme De Banane",
    "Creme de Cacao",
    "Creme de Cassis",
    "Creme de Mure",
    "Crown Royal",
    "Cucumber",
    "Cumin seed",
    "Daiquiri mix",
    "Dark rum",
    "demerara Sugar",
    "Dr. Pepper",
    "Drambuie",
    "Dry Vermouth",
    "Dubonnet Rouge",
    "Egg",
    "Egg white",
    "Egg yolk",
    "Elderflower cordial",
    "Espresso",
    "Everclear",
    "Falernum",
    "Figs",
    "Firewater",
    "Food coloring",
    "Frangelico",
    "Fresca",
    "Fresh Lemon Juice",
    "Fresh Lime Juice",
    "Fruit",
    "Fruit juice",
    "Fruit punch",
    "Galliano",
    "Gin",
    "Ginger",
    "Ginger ale",
    "Ginger Beer",
    "Ginger Syrup",
    "Godiva liqueur",
    "Gold rum",
    "Goldschlager",
    "Grain alcohol",
    "Grand Marnier",
    "Grape juice",
    "Grape Soda",
    "Grapefruit juice",
    "Grapefruit Juice",
    "Green Chartreuse",
    "Green Creme de Menthe",
    "Grenadine",
    "Guinness stout",
    "Half-and-half",
    "Heavy cream",
    "Honey",
    "Honey syrup",
    "Hot Chocolate",
    "Hot Damn",
    "Hot Sauce",
    "Ice",
    "Iced tea",
    "Irish cream",
    "Irish whiskey",
    "Islay single malt Scotch",
    "Jack Daniels",
    "Jägermeister",
    "Jello",
    "Jim Beam",
    "Kahlua",
    "Kiwi",
    "Kiwi liqueur",
    "Kool-Aid",
    "Lager",
    "Lavender",
    "Lemon",
    "Lemon juice",
    "Lemon peel",
    "Lemon-lime soda",
    "Lemonade",
    "Light cream",
    "Light rum",
    "Lillet",
    "Lillet Blanc",
    "Lime",
    "Lime juice",
    "Lime peel",
    "Lime vodka",
    "Limeade",
    "Malibu rum",
    "Mango",
    "Maple syrup",
    "Maraschino cherry",
    "Maraschino liqueur",
    "Marshmallows",
    "Melon Liqueur",
    "Mezcal",
    "Midori melon liqueur",
    "Milk",
    "Mint",
    "Mint syrup",
    "Mountain Dew",
    "Nutmeg",
    "Olive",
    "Olive Brine",
    "Orange",
    "Orange bitters",
    "Orange Curacao",
    "Orange juice",
    "Orange peel",
    "Oreo cookie",
    "Orgeat syrup",
    "Ouzo",
    "Papaya",
    "Passion fruit juice",
    "Passion fruit syrup",
    "Passoa",
    "Peach Bitters",
    "Peach brandy",
    "Peach nectar",
    "Peach schnapps",
    "Peach Vodka",
    "Peachtree schnapps",
    "Pepper",
    "Peppermint extract",
    "Pepsi Cola",
    "Pernod",
    "Peychaud bitters",
    "Pina colada mix",
    "Pineapple",
    "Pineapple juice",
    "Pineapple Syrup",
    "Pink lemonade",
    "Pisang Ambon",
    "Pisco",
    "Pomegranate juice",
    "Port",
    "Powdered sugar",
    "Prosecco",
    "Raspberry Liqueur",
    "Raspberry syrup",
    "Raspberry vodka",
    "Red Chili Flakes",
    "Red wine",
    "Ricard",
    "Root beer",
    "Rose",
    "Rosemary",
    "Rosemary Syrup",
    "Rosso Vermouth",
    "Ruby Port",
    "Rum",
    "Rye whiskey",
    "Rye Whiskey",
    "Salt",
    "Sambuca",
    "Sarsaparilla",
    "Schweppes Russchian",
    "Scotch",
    "Sherbet",
    "Sherry",
    "Sirup of roses",
    "Sloe gin",
    "Soda water",
    "Sour mix",
    "Southern Comfort",
    "Soy Sauce",
    "Spiced rum",
    "Sprite",
    "St. Germain",
    "Strawberries",
    "Strawberry schnapps",
    "Sugar",
    "Sugar syrup",
    "Surge",
    "Sweet and sour",
    "Sweet Vermouth",
    "Tabasco sauce",
    "Tea",
    "Tennessee whiskey",
    "Tequila",
    "Thyme",
    "Tia maria",
    "Tomato juice",
    "Tonic water",
    "Triple sec",
    "Vanilla",
    "Vanilla extract",
    "Vanilla ice-cream",
    "Vanilla syrup",
    "Vermouth",
    "Vodka",
    "Water",
    "Whipped cream",
    "Whiskey",
    "Whisky",
    "White Creme de Menthe",
    "White rum",
    "White Wine",
    "Wild Turkey",
    "Wine",
    "Worcestershire sauce",
    "Wormwood",
    "Yellow Chartreuse",
    "Yoghurt",
    "Yukon Jack",
    "Zima"
]